### ISSUE TITLE
pg_backup_ctl basebackup does not clean up lock on Linux

### ISSUE THREAD

**Issue by mbanck** [credativ/pg_backup_ctl#3]
If I run pg_backup_ctl basebackup, the lock file is left behind in the archive directory, even if the basebackup seemingly worked fine:

```
$ ls /srv/archive && pg_backup_ctl A /srv/archive/ basebackup && ls /srv/archive
base  log
base  log  pg_backup_ctl.base.lock
```

This is on Linux.

**Comment by mbanck** [comment]
Proposed patch:

[diff.txt](https://github.com/credativ/pg_backup_ctl/files/38426/diff.txt)

**Comment by psoo** [comment]
This is intentional. The presence of the lockfile doesn't mean the archive is locked. The actual locking is done via flock().

**Comment by mbanck** [comment]
Well I assumed so, I didn't mean to imply that locking itself was broken.

However, leaving behind lockfiles looks highly confusing to users to me. Then again, I did not see this in regular operation a lot, so maybe I hit a cornercase.
